{
 "title": "Router dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "traceId", "label": "Trace ID" }
  ]
 },
 "panels": [
  {
   "title": "Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(apollo_router_http_request_duration_seconds_bucket[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Subgraph request duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(subgraph, le) (rate(apollo_router_http_request_duration_seconds_bucket[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Traces",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
     "targets": [
      { "limit": 20, "query": "{}", "tableType": "traces" }
     ]
    }
   ]
  },
  { "title": "Query planner", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  { "title": "Traces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } }
 ]
}