POST http://router:4000/
Accept: application/json
Content-type: application/json
@/etc/vegeta/reviews.json

POST http://router:4000/
Accept: application/json
Content-type: application/json
@/etc/vegeta/products.json

POST http://router:4000/
Accept: application/json
Content-type: application/json
@/etc/vegeta/large.json

POST http://router:4000/
Accept: application/json
Content-type: application/json
@/etc/vegeta/reviews1.json

POST http://router:4000/
Accept: application/json
Content-type: application/json
@/etc/vegeta/products1.json

POST http://router:4000/
Accept: application/json
Content-type: application/json
@/etc/vegeta/large1.json

POST http://router:4000/
Accept: application/json
Content-type: application/json
@/etc/vegeta/reviews2.json

POST http://router:4000/
Accept: application/json
Content-type: application/json
@/etc/vegeta/products2.json

POST http://router:4000/
Accept: application/json
Content-type: application/json
@/etc/vegeta/large2.json

POST http://router:4000/
Accept: application/json
Content-type: application/json
@/etc/vegeta/reviews3.json

POST http://router:4000/
Accept: application/json
Content-type: application/json
@/etc/vegeta/products3.json

POST http://router:4000/
Accept: application/json
Content-type: application/json
@/etc/vegeta/large3.json

POST http://router:4000/
Accept: application/json
Content-type: application/json
@/etc/vegeta/reviews4.json

POST http://router:4000/
Accept: application/json
Content-type: application/json
@/etc/vegeta/products4.json

POST http://router:4000/
Accept: application/json
Content-type: application/json
@/etc/vegeta/large4.json

POST http://router:4000/
Accept: application/json
Content-type: application/json
@/etc/vegeta/reviews5.json

POST http://router:4000/
Accept: application/json
Content-type: application/json
@/etc/vegeta/products5.json

POST http://router:4000/
Accept: application/json
Content-type: application/json
@/etc/vegeta/reviews6.json

POST http://router:4000/
Accept: application/json
Content-type: application/json
@/etc/vegeta/products6.json

POST http://router:4000/
Accept: application/json
Content-type: application/json
@/etc/vegeta/reviews7.json

POST http://router:4000/
Accept: application/json
Content-type: application/json
@/etc/vegeta/products7.json

POST http://router:4000/
Accept: application/json
Content-type: application/json
@/etc/vegeta/reviews8.json

POST http://router:4000/
Accept: application/json
Content-type: application/json
@/etc/vegeta/products8.json

POST http://router:4000/
Accept: application/json
Content-type: application/json
@/etc/vegeta/reviews9.json

POST http://router:4000/
Accept: application/json
Content-type: application/json
@/etc/vegeta/products9.json
